---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr-operator 
  labels:
    control-plane: solr-operator
spec:
  selector:
    matchLabels:
      control-plane: solr-operator 
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: solr-operator 
    spec:
      serviceAccountName: solr-operator
      containers:
      - args:
        - -zk-operator=true
        image: bloomberg/solr-operator:latest
        imagePullPolicy: IfNotPresent
        name: solr-operator
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
